//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference_dt
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuesta_usuarioCN", Namespace="http://schemas.datacontract.org/2004/07/ClasesNegocio.mensaje")]
    public partial class respuesta_usuarioCN : object
    {
        
        private string estadoField;
        
        private string mensajeField;
        
        private string nickField;
        
        private string rolField;
        
        private string tokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nick
        {
            get
            {
                return this.nickField;
            }
            set
            {
                this.nickField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuestaCN", Namespace="http://schemas.datacontract.org/2004/07/ClasesNegocio.mensaje")]
    public partial class respuestaCN : object
    {
        
        private string estadoField;
        
        private string mensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="statesCN", Namespace="http://schemas.datacontract.org/2004/07/ClasesNegocio.datos")]
    public partial class statesCN : object
    {
        
        private string checkTimeEtField;
        
        private string commercialScoreField;
        
        private string dataQualityGradeField;
        
        private string dateField;
        
        private string dateCheckedField;
        
        private string dateModifiedField;
        
        private string deathField;
        
        private string deathConfirmedField;
        
        private string deathIncreaseField;
        
        private string deathProbableField;
        
        private string fipsField;
        
        private string gradeField;
        
        private string hashField;
        
        private string hospitalizedField;
        
        private string hospitalizedCumulativeField;
        
        private string hospitalizedCurrentlyField;
        
        private string hospitalizedDischargedField;
        
        private string hospitalizedIncreaseField;
        
        private string inIcuCumulativeField;
        
        private string inIcuCurrentlyField;
        
        private string lastUpdateEtField;
        
        private string negativeField;
        
        private string negativeIncreaseField;
        
        private string negativeRegularScoreField;
        
        private string negativeScoreField;
        
        private string negativeTestsAntibodyField;
        
        private string negativeTestsPeopleAntibodyField;
        
        private string negativeTestsViralField;
        
        private string onVentilatorCumulativeField;
        
        private string onVentilatorCurrentlyField;
        
        private string pendingField;
        
        private string posNegField;
        
        private string positiveField;
        
        private string positiveCasesViralField;
        
        private string positiveIncreaseField;
        
        private string positiveScoreField;
        
        private string positiveTestsAntibodyField;
        
        private string positiveTestsAntigenField;
        
        private string positiveTestsPeopleAntibodyField;
        
        private string positiveTestsPeopleAntigenField;
        
        private string positiveTestsViralField;
        
        private string probableCasesField;
        
        private string recoveredField;
        
        private string stateField;
        
        private string totalField;
        
        private string totalTestEncountersViralField;
        
        private string totalTestResultsField;
        
        private string totalTestResultsIncreaseField;
        
        private string totalTestResultsSourceField;
        
        private string totalTestsAntibodyField;
        
        private string totalTestsAntigenField;
        
        private string totalTestsPeopleAntibodyField;
        
        private string totalTestsPeopleAntigenField;
        
        private string totalTestsPeopleViralField;
        
        private string totalTestsViralField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string checkTimeEt
        {
            get
            {
                return this.checkTimeEtField;
            }
            set
            {
                this.checkTimeEtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string commercialScore
        {
            get
            {
                return this.commercialScoreField;
            }
            set
            {
                this.commercialScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dataQualityGrade
        {
            get
            {
                return this.dataQualityGradeField;
            }
            set
            {
                this.dataQualityGradeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateChecked
        {
            get
            {
                return this.dateCheckedField;
            }
            set
            {
                this.dateCheckedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateModified
        {
            get
            {
                return this.dateModifiedField;
            }
            set
            {
                this.dateModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string death
        {
            get
            {
                return this.deathField;
            }
            set
            {
                this.deathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deathConfirmed
        {
            get
            {
                return this.deathConfirmedField;
            }
            set
            {
                this.deathConfirmedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deathIncrease
        {
            get
            {
                return this.deathIncreaseField;
            }
            set
            {
                this.deathIncreaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deathProbable
        {
            get
            {
                return this.deathProbableField;
            }
            set
            {
                this.deathProbableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fips
        {
            get
            {
                return this.fipsField;
            }
            set
            {
                this.fipsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hash
        {
            get
            {
                return this.hashField;
            }
            set
            {
                this.hashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hospitalized
        {
            get
            {
                return this.hospitalizedField;
            }
            set
            {
                this.hospitalizedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hospitalizedCumulative
        {
            get
            {
                return this.hospitalizedCumulativeField;
            }
            set
            {
                this.hospitalizedCumulativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hospitalizedCurrently
        {
            get
            {
                return this.hospitalizedCurrentlyField;
            }
            set
            {
                this.hospitalizedCurrentlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hospitalizedDischarged
        {
            get
            {
                return this.hospitalizedDischargedField;
            }
            set
            {
                this.hospitalizedDischargedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hospitalizedIncrease
        {
            get
            {
                return this.hospitalizedIncreaseField;
            }
            set
            {
                this.hospitalizedIncreaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inIcuCumulative
        {
            get
            {
                return this.inIcuCumulativeField;
            }
            set
            {
                this.inIcuCumulativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inIcuCurrently
        {
            get
            {
                return this.inIcuCurrentlyField;
            }
            set
            {
                this.inIcuCurrentlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastUpdateEt
        {
            get
            {
                return this.lastUpdateEtField;
            }
            set
            {
                this.lastUpdateEtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string negative
        {
            get
            {
                return this.negativeField;
            }
            set
            {
                this.negativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string negativeIncrease
        {
            get
            {
                return this.negativeIncreaseField;
            }
            set
            {
                this.negativeIncreaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string negativeRegularScore
        {
            get
            {
                return this.negativeRegularScoreField;
            }
            set
            {
                this.negativeRegularScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string negativeScore
        {
            get
            {
                return this.negativeScoreField;
            }
            set
            {
                this.negativeScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string negativeTestsAntibody
        {
            get
            {
                return this.negativeTestsAntibodyField;
            }
            set
            {
                this.negativeTestsAntibodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string negativeTestsPeopleAntibody
        {
            get
            {
                return this.negativeTestsPeopleAntibodyField;
            }
            set
            {
                this.negativeTestsPeopleAntibodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string negativeTestsViral
        {
            get
            {
                return this.negativeTestsViralField;
            }
            set
            {
                this.negativeTestsViralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string onVentilatorCumulative
        {
            get
            {
                return this.onVentilatorCumulativeField;
            }
            set
            {
                this.onVentilatorCumulativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string onVentilatorCurrently
        {
            get
            {
                return this.onVentilatorCurrentlyField;
            }
            set
            {
                this.onVentilatorCurrentlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pending
        {
            get
            {
                return this.pendingField;
            }
            set
            {
                this.pendingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string posNeg
        {
            get
            {
                return this.posNegField;
            }
            set
            {
                this.posNegField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string positive
        {
            get
            {
                return this.positiveField;
            }
            set
            {
                this.positiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string positiveCasesViral
        {
            get
            {
                return this.positiveCasesViralField;
            }
            set
            {
                this.positiveCasesViralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string positiveIncrease
        {
            get
            {
                return this.positiveIncreaseField;
            }
            set
            {
                this.positiveIncreaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string positiveScore
        {
            get
            {
                return this.positiveScoreField;
            }
            set
            {
                this.positiveScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string positiveTestsAntibody
        {
            get
            {
                return this.positiveTestsAntibodyField;
            }
            set
            {
                this.positiveTestsAntibodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string positiveTestsAntigen
        {
            get
            {
                return this.positiveTestsAntigenField;
            }
            set
            {
                this.positiveTestsAntigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string positiveTestsPeopleAntibody
        {
            get
            {
                return this.positiveTestsPeopleAntibodyField;
            }
            set
            {
                this.positiveTestsPeopleAntibodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string positiveTestsPeopleAntigen
        {
            get
            {
                return this.positiveTestsPeopleAntigenField;
            }
            set
            {
                this.positiveTestsPeopleAntigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string positiveTestsViral
        {
            get
            {
                return this.positiveTestsViralField;
            }
            set
            {
                this.positiveTestsViralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string probableCases
        {
            get
            {
                return this.probableCasesField;
            }
            set
            {
                this.probableCasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recovered
        {
            get
            {
                return this.recoveredField;
            }
            set
            {
                this.recoveredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestEncountersViral
        {
            get
            {
                return this.totalTestEncountersViralField;
            }
            set
            {
                this.totalTestEncountersViralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestResults
        {
            get
            {
                return this.totalTestResultsField;
            }
            set
            {
                this.totalTestResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestResultsIncrease
        {
            get
            {
                return this.totalTestResultsIncreaseField;
            }
            set
            {
                this.totalTestResultsIncreaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestResultsSource
        {
            get
            {
                return this.totalTestResultsSourceField;
            }
            set
            {
                this.totalTestResultsSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestsAntibody
        {
            get
            {
                return this.totalTestsAntibodyField;
            }
            set
            {
                this.totalTestsAntibodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestsAntigen
        {
            get
            {
                return this.totalTestsAntigenField;
            }
            set
            {
                this.totalTestsAntigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestsPeopleAntibody
        {
            get
            {
                return this.totalTestsPeopleAntibodyField;
            }
            set
            {
                this.totalTestsPeopleAntibodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestsPeopleAntigen
        {
            get
            {
                return this.totalTestsPeopleAntigenField;
            }
            set
            {
                this.totalTestsPeopleAntigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestsPeopleViral
        {
            get
            {
                return this.totalTestsPeopleViralField;
            }
            set
            {
                this.totalTestsPeopleViralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestsViral
        {
            get
            {
                return this.totalTestsViralField;
            }
            set
            {
                this.totalTestsViralField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usCN", Namespace="http://schemas.datacontract.org/2004/07/ClasesNegocio.datos")]
    public partial class usCN : object
    {
        
        private string dateField;
        
        private string dateCheckedField;
        
        private string deathField;
        
        private string deathIncreaseField;
        
        private string hashField;
        
        private string hospitalizedField;
        
        private string hospitalizedCumulativeField;
        
        private string hospitalizedCurrentlyField;
        
        private string hospitalizedIncreaseField;
        
        private string inIcuCumulativeField;
        
        private string inIcuCurrentlyField;
        
        private string lastModifiedField;
        
        private string negativeField;
        
        private string negativeIncreaseField;
        
        private string onVentilatorCumulativeField;
        
        private string onVentilatorCurrentlyField;
        
        private string pendingField;
        
        private string posNegField;
        
        private string positiveField;
        
        private string positiveIncreaseField;
        
        private string recoveredField;
        
        private string statesField;
        
        private string totalField;
        
        private string totalTestResultsField;
        
        private string totalTestResultsIncreaseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateChecked
        {
            get
            {
                return this.dateCheckedField;
            }
            set
            {
                this.dateCheckedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string death
        {
            get
            {
                return this.deathField;
            }
            set
            {
                this.deathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deathIncrease
        {
            get
            {
                return this.deathIncreaseField;
            }
            set
            {
                this.deathIncreaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hash
        {
            get
            {
                return this.hashField;
            }
            set
            {
                this.hashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hospitalized
        {
            get
            {
                return this.hospitalizedField;
            }
            set
            {
                this.hospitalizedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hospitalizedCumulative
        {
            get
            {
                return this.hospitalizedCumulativeField;
            }
            set
            {
                this.hospitalizedCumulativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hospitalizedCurrently
        {
            get
            {
                return this.hospitalizedCurrentlyField;
            }
            set
            {
                this.hospitalizedCurrentlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hospitalizedIncrease
        {
            get
            {
                return this.hospitalizedIncreaseField;
            }
            set
            {
                this.hospitalizedIncreaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inIcuCumulative
        {
            get
            {
                return this.inIcuCumulativeField;
            }
            set
            {
                this.inIcuCumulativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inIcuCurrently
        {
            get
            {
                return this.inIcuCurrentlyField;
            }
            set
            {
                this.inIcuCurrentlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastModified
        {
            get
            {
                return this.lastModifiedField;
            }
            set
            {
                this.lastModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string negative
        {
            get
            {
                return this.negativeField;
            }
            set
            {
                this.negativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string negativeIncrease
        {
            get
            {
                return this.negativeIncreaseField;
            }
            set
            {
                this.negativeIncreaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string onVentilatorCumulative
        {
            get
            {
                return this.onVentilatorCumulativeField;
            }
            set
            {
                this.onVentilatorCumulativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string onVentilatorCurrently
        {
            get
            {
                return this.onVentilatorCurrentlyField;
            }
            set
            {
                this.onVentilatorCurrentlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pending
        {
            get
            {
                return this.pendingField;
            }
            set
            {
                this.pendingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string posNeg
        {
            get
            {
                return this.posNegField;
            }
            set
            {
                this.posNegField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string positive
        {
            get
            {
                return this.positiveField;
            }
            set
            {
                this.positiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string positiveIncrease
        {
            get
            {
                return this.positiveIncreaseField;
            }
            set
            {
                this.positiveIncreaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recovered
        {
            get
            {
                return this.recoveredField;
            }
            set
            {
                this.recoveredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string states
        {
            get
            {
                return this.statesField;
            }
            set
            {
                this.statesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestResults
        {
            get
            {
                return this.totalTestResultsField;
            }
            set
            {
                this.totalTestResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTestResultsIncrease
        {
            get
            {
                return this.totalTestResultsIncreaseField;
            }
            set
            {
                this.totalTestResultsIncreaseField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_dt.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Autenticar", ReplyAction="http://tempuri.org/IService1/AutenticarResponse")]
        System.Threading.Tasks.Task<ServiceReference_dt.respuesta_usuarioCN> AutenticarAsync(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarUsuario", ReplyAction="http://tempuri.org/IService1/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReference_dt.respuestaCN> RegistrarUsuarioAsync(string usuario, string clave, long id_rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Verificar_rol_usuario", ReplyAction="http://tempuri.org/IService1/Verificar_rol_usuarioResponse")]
        System.Threading.Tasks.Task<bool> Verificar_rol_usuarioAsync(string usuario, string token, string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Listar_states", ReplyAction="http://tempuri.org/IService1/Listar_statesResponse")]
        System.Threading.Tasks.Task<ServiceReference_dt.statesCN[]> Listar_statesAsync(string usuario, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Listar_us", ReplyAction="http://tempuri.org/IService1/Listar_usResponse")]
        System.Threading.Tasks.Task<ServiceReference_dt.usCN[]> Listar_usAsync(string usuario, string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IService1Channel : ServiceReference_dt.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference_dt.IService1>, ServiceReference_dt.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference_dt.respuesta_usuarioCN> AutenticarAsync(string usuario, string clave)
        {
            return base.Channel.AutenticarAsync(usuario, clave);
        }
        
        public System.Threading.Tasks.Task<ServiceReference_dt.respuestaCN> RegistrarUsuarioAsync(string usuario, string clave, long id_rol)
        {
            return base.Channel.RegistrarUsuarioAsync(usuario, clave, id_rol);
        }
        
        public System.Threading.Tasks.Task<bool> Verificar_rol_usuarioAsync(string usuario, string token, string rol)
        {
            return base.Channel.Verificar_rol_usuarioAsync(usuario, token, rol);
        }
        
        public System.Threading.Tasks.Task<ServiceReference_dt.statesCN[]> Listar_statesAsync(string usuario, string token)
        {
            return base.Channel.Listar_statesAsync(usuario, token);
        }
        
        public System.Threading.Tasks.Task<ServiceReference_dt.usCN[]> Listar_usAsync(string usuario, string token)
        {
            return base.Channel.Listar_usAsync(usuario, token);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("https://wcfappdesarrollo.azurewebsites.net/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IService1,
        }
    }
}
